server:
  port: 8080
  indexingAvailable: true

spring.profiles.active: mysql

spring.jpa.show-sql: false

spring:
  jpa.properties.hibernate.enable_lazy_load_no_trans: true

  thymeleaf:
    enabled: true
    encoding: UTF-8

  messages.basename: lang.messages


logging:
  level.root: INFO
  file.name: logs/info.log

config:
  forSitesThreadNumber: 12
  forPagesThreadNumber: 12
  repeatedPageCount: 14
  maxPagesInSite: 3000

  sites:
    - url: http://www.playback.ru
      name: PlayBack.ru
      pause: 0
    - url: https://volochek.life
      name: Вышний Волочёк
      pause: 0
    - url: http://radiomv.ru
      name: Милицейская волна
      pause: 0
    - url: https://earth.google.com
      name: GoogleEarth
      pause: 0
    - url: https://юургау.рф
      name: юургау
      pause: 0
    - url: https://lichess.org
      name: Lichess
      pause: 0
    - url: https://jut.su
      name: jut.su
      pause: 0
    - url: https://www.lenta.ru
      name: Лента.ру
      pause: 500

